# fly.toml app configuration file generated for zifnab-www on 2023-11-26T00:39:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zifnab-www"
primary_region = "sea"

[build]

[http_service]
  internal_port = 80
  force_https = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  XDG_CONFIG_HOME = "/data/xdg/"
